name: google_maps_demo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.11.0
  location: ^5.0.0
  maps_toolkit: ^3.0.0
  firebase_core: ^3.12.1
  flutter_dotenv: ^5.2.1
  cloud_firestore: ^5.6.5
  intl: ^0.18.1
  http: ^1.3.0
  custom_info_window: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - .env
    - assets/marker1.png
    - assets/weather_back.png
    - assets/fishing_spot.png
    
  uses-material-design: true

