// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdYFzbhitduHd2N2WwBpAbnP0wLum4WYg',
    appId: '1:219284981005:web:6f8b3951a536fc4a3f1c44',
    messagingSenderId: '219284981005',
    projectId: 'gdg-tamilnaduapp',
    authDomain: 'gdg-tamilnaduapp.firebaseapp.com',
    storageBucket: 'gdg-tamilnaduapp.firebasestorage.app',
    measurementId: 'G-L2Y9ER3E0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH5fxRG1q6yFkuCA29BIHDyj8zISa7Mgo',
    appId: '1:219284981005:android:0c796c6f0eb8e9de3f1c44',
    messagingSenderId: '219284981005',
    projectId: 'gdg-tamilnaduapp',
    storageBucket: 'gdg-tamilnaduapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXFEQ8zXzG4Fu_xGZFtB8mdNl85l5H9KA',
    appId: '1:219284981005:ios:1e1f2919e734e62f3f1c44',
    messagingSenderId: '219284981005',
    projectId: 'gdg-tamilnaduapp',
    storageBucket: 'gdg-tamilnaduapp.firebasestorage.app',
    iosBundleId: 'com.example.googleMapsDemo',
  );
}
